language: android

jdk: oraclejdk8

sudo: required # more memory
dist: trusty
group: deprecated-2017Q4

before_install:
  - yes | sdkmanager "platforms;android-27"

android:
  components:
    - tools
    - platform-tools
    - tools # called twice to get the newest android sdk tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository

env:
  - FLAVOR="openhpi"
  - FLAVOR="opensap"
  - FLAVOR="moochouse"
  - FLAVOR="openwho"

script:
   - ./gradlew assemble${FLAVOR}Debug test${FLAVOR}DebugUnitTest connected${FLAVOR}DebugAndroidTest
